name: "cargo-machete"
description: "A github action for cargo machete"
author: "Cargo machete community"
inputs:
  cargo_manifest_dir:
    description: "The directory of the Cargo.toml file"
    required: false
    default: "."
branding:
  color: "gray-dark"
  icon: "code"
runs:
  using: composite
  steps:
    - name: Install cargo-machete
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-machete
    - name: Machete
      uses: actions-rs/cargo@v1
      with:
        command: machete
        args: ${{ inputs.cargo_manifest_dir }}
